### ISSUE TITLE
新的 tdx 觀光 api，無法在子類別後面包含斜線，這樣對某些api套件會失效。會對不少公司有影響。

### ISSUE THREAD

**Issue by Star-Tree** [tdxmotc/SampleCode#13]
新的 tdx 觀光 api，無法在子類別後面包含斜線，這樣對某些重要套件會失效。會對不少公司有影響。

舊的 ptx api 可以包含子類別後面有斜線。這樣對於 axios 等，這類常見api 套件，做串接包裝會很方便。

例如:
https://ptx.transportdata.tw/MOTC/v2/Tourism/ScenicSpot?$filter=contains(ScenicSpotID,'C1_379000000A_000212')&$format=JSON

https://ptx.transportdata.tw/MOTC/v2/Tourism/ScenicSpot/?$filter=contains(ScenicSpotID,'C1_379000000A_000212')&$format=JSON

上述兩條網址，在 舊的 ptx api ，ScenicSpot後面可以包含斜線。

新的 tdx api 則無法包含斜線，這樣對於接api 的套件的相容性，包裝會非常差..會有bug 無法呼叫的問題。

新的 tdx api，我也給2條網址

如下:
https://tdx.transportdata.tw/api/basic/v2/Tourism/ScenicSpot?$filter=contains(ScenicSpotID,'C1_379000000A_000212')&$format=JSON

https://tdx.transportdata.tw/api/basic/v2/Tourism/ScenicSpot/?$filter=contains(ScenicSpotID,'C1_379000000A_000212')&$format=JSON

上述都是 請求一樣的內容，但子類別 ScenicSpot後面，第1條網址，前者無斜線，可以得到結果。
但第2條網址，ScenicSpot 子類別後面 加上斜線，就會無法得到對應的結果。

這個相容性會變差，會造成 眾多 api套件整合包裝時，造成bug，建議可以趕快修正。

我發現到，建議可以趕快改善，因為應該不少公司接下來12/01換 api 都會造成影響。

我是自己做 side-project 發現的，來信叨擾了，感謝你們。

**Comment by tdxmotc** [comment]
您好
TDX平台今日已更新url路徑規則，使其支援以斜線做結尾。
謝謝您提供寶貴的意見!

**Comment by Star-Tree** [comment]
我這邊也已確認測試你們的 API 路徑規則，相容性方面是完整的，資料也有做更新。
如有問題，我也會繼續做回報。
感謝TDX平台的各位貢獻者。謝謝大家的努力~
