### ISSUE TITLE
請問是不是突然改版了，原本的驗證方式都無法用了..

### ISSUE THREAD

**Issue by Star-Tree** [tdxmotc/SampleCode#2]
想問 能否改回原本的 驗證登入方式，不然改來改去好像很亂。

**Comment by tdxmotc** [comment]
您好  
TDX平臺目前為PTX/Traffic/Parking/GIS-T等子系統的API統一代理站，並採取和原子系統不一樣的權限驗證方式。   
但原先子系統(PTX/Traffic/Parking/GIS-T)的API路徑與權限驗證方式皆維持不變，您還是可以使用舊有方式介接子系統API。  
若改介接TDX API，才需參考本處所提供的範例程式進行修正。  

TDX平臺與其他子系統之間的差異，可參考官網【常見問題】的第四點說明:  
https://tdx.transportdata.tw/about/faq
